# The basic structure remains the same but with minor optimizations:
version: 1.0

deploy:
  # This section is used for the FIRST deployment of each branch
  bootstrap:
    excludes:
      - tests
      - node_modules
      - DOCKER_ENV
      - docker_tag
      - output.log
      - storage
      - .env
      - vendor

    post-deployment-remote-commands:
      - composer install --no-dev --optimize-autoloader
      - chmod -R 775 storage bootstrap/cache
      - php artisan storage:link
      - php artisan config:clear
      - php artisan cache:clear
      - php artisan route:clear
      - php artisan view:clear
      - php artisan config:cache
      - php artisan route:cache
      - php artisan view:cache
      - php artisan migrate --force

  # This section is used for ALL further deployments
  recurring:
    excludes:
      - tests
      - node_modules
      - DOCKER_ENV
      - docker_tag
      - output.log
      - storage
      - .env
      - vendor

    pre-deployment-remote-commands:
      - php artisan down

    post-deployment-remote-commands:
      - composer install --no-dev --optimize-autoloader
      - chmod -R 775 storage bootstrap/cache
      - php artisan storage:link
      - php artisan config:clear
      - php artisan cache:clear
      - php artisan route:clear
      - php artisan view:clear
      - php artisan config:cache
      - php artisan route:cache
      - php artisan view:cache
      - php artisan migrate --force
      - php artisan up
