# The basic structure remains the same but with minor optimizations:
version: 1.0

deploy:
  bootstrap:
    excludes:
      - tests
      - node_modules
      - DOCKER_ENV
      - docker_tag
      - output.log
      - .env
    post-deployment-remote-commands:
      - echo "Starting bootstrap post-deployment commands..."
      - chmod -R 775 storage bootstrap/cache
      - chmod -R 775 storage/logs
      - php artisan storage:link
      - php artisan config:clear
      - php artisan config:cache
      - php artisan route:cache
      - php artisan view:cache
      - php artisan migrate --force
      - echo "Displaying Laravel log (last 20 lines):"
      - tail -n 20 storage/logs/laravel.log || echo "No Laravel log found"

  recurring:
    excludes:
      - tests
      - node_modules
      - DOCKER_ENV
      - docker_tag
      - output.log
      - .env
    pre-deployment-remote-commands:
      - echo "Bringing site down for recurring deployment..."
      - php artisan down
    post-deployment-remote-commands:
      - echo "Starting recurring post-deployment commands..."
      - chmod -R 775 storage bootstrap/cache
      - chmod -R 775 storage/logs
      - php artisan storage:link
      - php artisan config:clear
      - php artisan config:cache
      - php artisan route:cache
      - php artisan view:cache
      - php artisan migrate --force
      - echo "Displaying Laravel log (last 20 lines):"
      - tail -n 20 storage/logs/laravel.log || echo "No Laravel log found"
