# The basic structure remains the same but with minor optimizations:
version: 1.0

deploy:
  bootstrap:
    excludes:
      - tests
      - node_modules
      - DOCKER_ENV
      - docker_tag
      - output.log
      - .env
    post-deployment-remote-commands:
      - chmod -R 775 storage bootstrap/cache
      - chmod -R 775 storage/logs
      - php artisan storage:link
      - php artisan config:clear
      - php artisan config:cache
      - php artisan route:cache
      - php artisan view:cache
      - php artisan migrate --force
      - cat storage/logs/laravel.log || echo "No Laravel log found"
      

  recurring:
    excludes:
      - tests
      - node_modules
      - DOCKER_ENV
      - docker_tag
      - output.log
      - .env
    pre-deployment-remote-commands:
      - php artisan down
    post-deployment-remote-commands:
      - chmod -R 775 storage bootstrap/cache
      - chmod -R 775 storage/logs
      - php artisan storage:link
      - php artisan config:clear
      - php artisan config:cache
      - php artisan route:cache
      - php artisan view:cache
      - php artisan migrate --force
      - cat storage/logs/laravel.log || echo "No Laravel log found"
   

