# The basic structure remains the same but with minor optimizations:
version: 1.0

deploy:
  bootstrap:
    excludes:
      - tests
      - node_modules
      - DOCKER_ENV
      - docker_tag
      - output.log
    post-deployment-remote-commands:
      - find $(pwd) -type f -not -path "$(pwd)/logs/*" -exec chmod 664 {} \;
      - find $(pwd) -type d -not -name "logs" -exec chmod 775 {} \;
      - chmod -R o+w storage bootstrap/cache
      - php artisan migrate --force
      - php artisan optimize:clear
      - php artisan storage:link
      - php artisan optimize
      - php artisan up

  recurring:
    excludes:
      - tests
      - node_modules
      - DOCKER_ENV
      - docker_tag
      - output.log
      - storage
    pre-deployment-remote-commands:
      - php artisan down
    post-deployment-remote-commands:
      - find $(pwd) -type f -not -path "$(pwd)/logs/*" -exec chmod 664 {} \;
      - find $(pwd) -type d -not -name "logs" -exec chmod 775 {} \;
      - chmod -R o+w storage bootstrap/cache
      - php artisan migrate --force
      - php artisan optimize:clear
      - php artisan storage:link
      - php artisan optimize
      - php artisan up

runtime:
  cron-jobs:
    - command: php /home/your-path-to-app/artisan schedule:run  # Example Laravel cron job
      schedule: 0 5 * * *  # Run every day at 5:00 AM
